sudo: false
language: ruby
rvm: 2.5
cache: bundler

branches:
  only:
  - master

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle update

matrix:
  include:
  - name: Rubocop
    script: bundle exec rubocop -S -D -E
  - name: bench
    script: ./bench
